---
# handlers file for apps

- name: enable "{{ apps_package }}" service
  service:
    name: "{{ apps_package }}"
    enabled: yes

- name: restart "{{ apps_package }}" service
  service:
    name: "{{ apps_package }}"
    state: restarted
