---
# handlers file for apps

- name: enable "{{ package }}" service
  service:
    name: "{{ package }}"
    enabled: yes

- name: restart "{{ package }}" service
  service:
    name: "{{ package }}"
    state: restarted
