---
# handlers file for frontends

- name: enable "{{ frontends_package }}" service
  service:
    name: "{{ frontends_package }}"

- name: restart "{{ frontends_package }}" service
  service:
    name: "{{ frontends_package }}"
    state: restarted
