---
# handlers file for frontends

- name: enable "{{ package }}" service
  service:
    name: "{{ package }}"

- name: restart "{{ package }}" service
  service:
    name: "{{ package }}"
    state: restarted
