---
# tasks file for frontends

- name: install "{{ package }}"
  package:
    name: "{{ package }}"
    state: latest
  notify:
   - enable "{{ package }}" service
   - restart "{{ package }}" service

- name: configure "{{ package }}"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
   - enable "{{ package }}" service
   - restart "{{ package }}" service
