---
# tasks file for frontends

- name: install "{{ frontends_package }}"
  package:
    name: "{{ frontends_package }}"
    state: latest
  notify:
   - enable "{{ frontends_package }}" service
   - restart "{{ frontends_package }}" service

- name: configure "{{ frontends_package }}"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
   - enable "{{ frontends_package }}" service
   - restart "{{ frontends_package }}" service
