---
# tasks file for postgres

# Install > Enable > Configure > Start

- name: install haproxy
  package:
    name: haproxy
    state: latest
  notify: restart haproxy service

- name: enable haproxy service
  service:
    name: haproxy
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy service
