---
# tasks file for apps

- name: install "{{ package }}"
  package:
    name: "{{ package }}"
    state: latest
  notify: 
   - enable "{{ package }}" service
   - restart "{{ package }}" service

- name: config create ansible "{{ package }}" directory
  file:
    path: "{{ basedir }}"
    state: directory

- name: config copy static index.html to "{{ package }}" webapps/ROOT/index.html
  template:
    src: index.html.j2
    dest: "{{ basedir }}/index.html"
    mode: 0644
  notify: 
   - enable "{{ package }}" service
   - restart "{{ package }}" service
