---
# tasks file for smoketest

- name: test loadbalancer response
  uri:
    url: "{{ smoketest_url }}"
    return_content: yes
  register: loadbalancer_response

- fail:
    msg: "site not returning expected content"
  when: "'Ansible' not in loadbalancer_response.content"
